param(
    [string]$SdkPath = (Join-Path $env:LOCALAPPDATA "Android\Sdk")
)

$ErrorActionPreference = "Stop"
$repoRoot = $PSScriptRoot
$androidProject = Join-Path $repoRoot "BankingMobileApp"
$localProperties = Join-Path $androidProject "local.properties"

if (-not (Test-Path -LiteralPath $SdkPath)) {
    throw "Khong tim thay Android SDK tai '$SdkPath'. Mo Android Studio > SDK Manager de cai SDK, hoac truyen -SdkPath <duong-dan-sdk>."
}

$platform = Join-Path $SdkPath "platforms\android-35"
$buildTools = Join-Path $SdkPath "build-tools\35.0.0"
if (-not (Test-Path -LiteralPath $platform)) {
    throw "Thieu Android SDK Platform 35 tai '$platform'. Hay cai API 35 trong SDK Manager."
}
if (-not (Test-Path -LiteralPath $buildTools)) {
    throw "Thieu Android SDK Build-Tools 35.0.0 tai '$buildTools'. Hay cai trong SDK Manager."
}

$escapedSdkPath = $SdkPath.Replace("\", "\\").Replace(":", "\:")
$content = @(
    "## Generated by setup-android-sdk.ps1. Do not commit this file."
    "sdk.dir=$escapedSdkPath"
) -join [Environment]::NewLine

[System.IO.File]::WriteAllText($localProperties, $content + [Environment]::NewLine)
Write-Host "Da tao: $localProperties"
Write-Host "Android SDK: $SdkPath"
